waylandloginmanager: save loginmanager display logs uder /var/log/waylandloginmanager/loginmanagerdisplays and update diff
git-svn-id: https://svn.code.sf.net/p/rebeccablackos/code@5522 b52b6941-3400-464c-9f42-43200397181c

diff --git a/rebeccablackos_files/usr/share/RBOS_PATCHES/waylandloginmanagerkdialog.diff b/rebeccablackos_files/usr/share/RBOS_PATCHES/waylandloginmanagerkdialog.diff
--- a/rebeccablackos_files/usr/share/RBOS_PATCHES/waylandloginmanagerkdialog.diff
+++ b/rebeccablackos_files/usr/share/RBOS_PATCHES/waylandloginmanagerkdialog.diff
@@ -1,5 +1,5 @@
---- usr/bin/waylandloginmanager	2018-01-04 08:38:13.633255763 -0500
-+++ usr/bin/waylandloginmanagerkdialog	2018-01-04 08:55:12.268972926 -0500
+--- usr/bin/waylandloginmanager	2018-02-11 14:25:48.304355050 -0500
++++ usr/bin/waylandloginmanagerkdialog	2018-02-11 14:31:21.719236014 -0500
 @@ -18,9 +18,9 @@
  
  #This script is the WaylandLoginManager it handles a graphical login for the user, and allows the user to start multiple types of Wayland sessions, specified in wesession files, and it supports autologin, mounting of ecryptfs home directories, and user switching. It supports watching the active session until it fails, so that it swiches back to the needed TTY for the user.
@@ -55,7 +55,7 @@
    TERMINALCMD="runuser -u $LOGINMANAGERDISPLAYUSER -m -- vte"
  
    #Detect hardware abilities, first try to see if the system has kernel mode setting, then try framebuffer. if both aren't supported, bring up a text mode dialog
-@@ -837,21 +841,12 @@
+@@ -837,22 +841,13 @@
    done
  }
  
@@ -63,7 +63,8 @@
 +#This function takes three arguments. The first is the number of seconds to wait, and the second is the string to show in the dialog. it shows a dialog with a progress bar to count down the specified time, with the string. The third is the seat to display it on
  function DialogWait
  {
-   export WAYLAND_DISPLAY=loginmanagerdisplay_"$3"
+   SeatFileName=${SeatFileNames[$(GetStartedSeatIndex $3)]}
+   export WAYLAND_DISPLAY=loginmanagerdisplay_"$SeatFileName"
    SetFallbackEnvironmentVariables $3
 -  waitseconds=$1
 -  displaystring="$2"
@@ -79,7 +80,7 @@
  }
  
  #This function takes 1 argument, the seat that the loginmanagerdisplay belongs to, and waits for the loginmanagerdisplay to startup
-@@ -923,10 +918,10 @@
+@@ -926,10 +921,10 @@
        SeatSupportedBackendsString+="FB "
      fi
    fi
@@ -92,7 +93,7 @@
    while read SESSIONFILE
    do
      IsExecutable=$(find $SESSIONFILE |wc -l)
-@@ -1127,7 +1122,7 @@
+@@ -1130,7 +1125,7 @@
    done < <(find $WSESSIONSPATH -maxdepth 1 -name "*\.desktop" -type f | sort )
  
  
@@ -101,7 +102,7 @@
    if [[ ! -z $WSESSIONLIST ]]
    then
      PROMPTED=1
-@@ -1147,13 +1142,16 @@
+@@ -1150,13 +1145,16 @@
        then
          WSESSIONPICKLIST+=$'\n'
        fi
@@ -122,7 +123,7 @@
      CancelOrOK=$?
      if [[ $CancelOrOK != 0 ]]
      then
-@@ -1171,7 +1169,7 @@
+@@ -1174,7 +1172,7 @@
    then 
      if [[ $PROMPTED == 1 ]]
      then
@@ -131,7 +132,7 @@
      else
        WriteToLog "No sessions installed in $WSESSIONSPATH or no sessions are enabled, or are missing files specified by NeedsFile values. Defaulting to the Default Weston Desktop Shell"
      fi
-@@ -1278,7 +1276,7 @@
+@@ -1283,7 +1281,7 @@
  
  This is the optimal way to run Weston or other Wayland servers."
    fi
@@ -140,7 +141,7 @@
  
  $BACKENDSTRING
  
-@@ -1302,12 +1300,6 @@
+@@ -1308,12 +1306,6 @@
    ((NumberOfSessions--))
  
    #go thorugh each session, reading the arrays containing information about the sessions. to build the SessionList variable
@@ -153,7 +154,7 @@
    RunningSeatSessions=($(loginctl show-seat "$1" -p Sessions --value 2>/dev/null))
    while [[ $NumberOfSessions -ge 0 ]]
    do
-@@ -1330,11 +1322,7 @@
+@@ -1336,11 +1328,7 @@
          then
            SessionList+=$'\n'
          fi
@@ -166,7 +167,7 @@
        fi
      fi
      ((NumberOfSessions--))
-@@ -1345,19 +1333,17 @@
+@@ -1351,19 +1339,17 @@
      SessionList+=$'\n'
    fi
    SessionList+="-1"$'\n'
@@ -192,7 +193,7 @@
    if [[ $CancelOrOK != 0 ]]
    then
      exit 0
-@@ -1386,7 +1372,7 @@
+@@ -1392,7 +1378,7 @@
          #hand over the logind session ID to allow desktop permissions to work.
          loginctl activate $ChangeSessionID &>/dev/null
        else
@@ -201,7 +202,7 @@
        fi
      fi
    fi
-@@ -1621,26 +1607,30 @@
+@@ -1629,26 +1615,30 @@
      then
        UserDisplayName=$UserName
      fi
@@ -240,7 +241,7 @@
    if [[ $CancelOrOK != 0 ]]
    then
      exit 0
-@@ -1648,9 +1638,9 @@
+@@ -1656,9 +1646,9 @@
    #if there is no user selected or if the LOGINUSER is -1, as in the user opted to enter a username manually prompt for the username with a text dialog
    if [[ -z $LOGINUSER || $LOGINUSER == -1 ]]
    then
@@ -252,7 +253,7 @@
      if [[ $CancelOrOK != 0 ]]
      then
        exit 0
-@@ -1666,9 +1656,9 @@
+@@ -1674,9 +1664,9 @@
    if [[ $SessionTTY -ne -1 ]]
    then
      #Prompt for the users password
@@ -264,7 +265,7 @@
      if [[ $CancelOrOK != 0 ]]
      then
        exit 0
-@@ -1680,23 +1670,23 @@
+@@ -1688,24 +1678,24 @@
      unset USERPASSWORD
      if [[ $passwordresult != 0 ]]
      then
@@ -274,7 +275,7 @@
      fi
    else
 -    $ZENITYCMD --warning --text="Not Enough TTYs!" 2>/dev/null
-+    $KDIALOGCMD --title="System Error" --error "Not Enough TTYs!" 2>/dev/nullll
++    $KDIALOGCMD --title="System Error" --error "Not Enough TTYs!" 2>/dev/null
      WriteToLog "Not Enough TTYs for user login!"
    fi
  }
@@ -285,14 +286,15 @@
  #It takes 1 argument, the seat to display the dialogs on
  function LeavePrompt
  {
-   export WAYLAND_DISPLAY=loginmanagerdisplay_"$1"
+   SeatFileName=${SeatFileNames[$(GetStartedSeatIndex $1)]}
+   export WAYLAND_DISPLAY=loginmanagerdisplay_"$SeatFileName"
    SetFallbackEnvironmentVariables $1
 -  #The first line is sent to the zenity dialog is the actual command it sets the ACTION variable to be. the second line is what it appears as in the Zenity dialog for the user.
 +  #The first line is sent to the dialog is the actual command it sets the ACTION variable to be. the second line is what it appears as in the dialog for the user.
    CanPowerOff=$(dbus-send --print-reply --system --dest=org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager.CanPowerOff |grep -c yes)
    if [[ $CanPowerOff == 1 ]]
    then
-@@ -1752,16 +1742,22 @@
+@@ -1761,16 +1751,22 @@
      ACTIONSTRING+=$'\n'
      ACTIONSTRING+="Hibernate Computer"
    fi
@@ -318,7 +320,7 @@
    CONFIRM=$?
    if [[ $CONFIRM != 0 ]]
    then
-@@ -1795,7 +1791,7 @@
+@@ -1804,7 +1800,7 @@
    #if the selected action failed, tell the user
    if [[ $RESULT != 0 ]]
    then
@@ -327,7 +329,7 @@
    fi
  }
  
-@@ -2107,7 +2103,7 @@
+@@ -2118,7 +2114,7 @@
    #Wait until the loginmanagerdisplay becomes availible
    DisplayServerWait "$1"
    ChooseSessionType "$1"
@@ -336,7 +338,7 @@
    CancelOrOK=$?
    if [[ $CancelOrOK != 0 ]]
    then
-@@ -2132,7 +2128,7 @@
+@@ -2143,7 +2139,7 @@
      fi
      StartUserSession "$AutoSessionTTY" "$1" "$AUTOLOGINUSER" 1 "$WSESSIONDATA" &
    else
@@ -345,7 +347,7 @@
      WriteToLog "Not Enough TTYs for autologin!"
    fi
  }
-@@ -2166,22 +2162,27 @@
+@@ -2178,22 +2174,27 @@
    SetFallbackEnvironmentVariables $1
    #wait for the loginmanagerdisplay
    DisplayServerWait "$1"
@@ -368,19 +370,19 @@
 -    ActionMenu+="\nDebug\nTerminal Login..."
 +    ActionMenu+=$'\n'"Debug"$'\n'"Terminal Login..."
    fi
--  USERACTION=$(echo -e "$ActionMenu"|$ZENITYCMD  --title="Login Manager" --height=300 --hide-column 1 --separator="\n" --list --column action --column display --hide-header --text "Select an Action"  2>> /var/log/loginmanagerdisplays/loginmanagerdisplay_"$1".log; exit ${PIPESTATUS[1]})
+-  USERACTION=$(echo -e "$ActionMenu"|$ZENITYCMD  --title="Login Manager" --height=300 --hide-column 1 --separator="\n" --list --column action --column display --hide-header --text "Select an Action"  2>> /var/log/waylandloginmanager/loginmanagerdisplays/loginmanagerdisplay_"$SeatFileName".log; exit ${PIPESTATUS[1]})
 -ZENITYSTATUS=$?
 +
 +  IFS=$'\n'
 +  ActionMenu=($ActionMenu)
 +  unset IFS
 +
-+  USERACTION=$($KDIALOGCMD --title="Login Manager" --menu "Select an Action" -- "${ActionMenu[@]}"  2>> /var/log/loginmanagerdisplays/loginmanagerdisplay_"$1".log)
++  USERACTION=$($KDIALOGCMD --title="Login Manager" --menu "Select an Action" -- "${ActionMenu[@]}"  2>> /var/log/waylandloginmanager/loginmanagerdisplays/loginmanagerdisplay_"$SeatFileName".log)
 +  DIALOGSTATUS=$?
    #If the useraction exists (the user did not click cancel), then send the command to the loginmanager_control
    if [[ ! -z $USERACTION ]]
    then
-@@ -2189,12 +2190,12 @@
+@@ -2201,12 +2202,12 @@
    else
      $SLEEPCMD .1
    fi
