build_core: Make the script error out when a build script does not define PackageInstallSource
git-svn-id: https://svn.code.sf.net/p/rebeccablackos/code@9013 b52b6941-3400-464c-9f42-43200397181c

diff --git a/rebeccablackos_files/usr/bin/build_core b/rebeccablackos_files/usr/bin/build_core
--- a/rebeccablackos_files/usr/bin/build_core
+++ b/rebeccablackos_files/usr/bin/build_core
@@ -172,9 +172,10 @@ function RunDownloadAndOrBuild
     function PackageCompileSource { :; }
   fi
 
+  #If a build script doesn't define a PackageInstallSource, handle that as a failure
   if ! declare -F PackageInstallSource &> /dev/null
   then
-    function PackageInstallSource { :; }
+    function PackageInstallSource { exit 1; }
   fi
 
   if ! declare -F PackagePostInstall &> /dev/null
