build_core: log a file of packages that fail to compile properly
git-svn-id: https://svn.code.sf.net/p/rebeccablackos/code@4689 b52b6941-3400-464c-9f42-43200397181c

diff --git a/rebeccablackos_files/usr/bin/build_core b/rebeccablackos_files/usr/bin/build_core
--- a/rebeccablackos_files/usr/bin/build_core
+++ b/rebeccablackos_files/usr/bin/build_core
@@ -622,13 +622,18 @@ function MakeAndInstall()
 
     STARTTIME=\$(date +%s)
     PackageInstallSource 2>&1 | tee \"/$SOURCEDIR/$SOURCENAME/Logs/PackageInstallSource\"
+    PackageInstallSourceResult=\${PIPESTATUS[0]}
     ENDTIME=\$(date +%s)
     echo \"PackageInstallSource finished in \$((ENDTIME-STARTTIME)) seconds\" 2>&1 | tee -a \"/$SOURCEDIR/$SOURCENAME/Logs/PackageInstallSource\"
 
     STARTTIME=\$(date +%s)
     PackagePostInstall 2>&1 | tee \"/$SOURCEDIR/$SOURCENAME/Logs/PackagePostInstall\"
     ENDTIME=\$(date +%s)
-    echo \" PackagePostInstall finished in \$((ENDTIME-STARTTIME)) seconds\" 2>&1 | tee -a \"/$SOURCEDIR/$SOURCENAME/Logs/PackagePostInstall\"
+    echo \" PackagePostInstall finished in \$((ENDTIME-STARTTIME)) seconds with result \$PackageInstallSourceResult\" 2>&1 | tee -a \"/$SOURCEDIR/$SOURCENAME/Logs/PackagePostInstall\"
+    if [[ \$PackageInstallSourceResult != 0 ]]
+    then
+      echo $SOURCENAME >> \"/$SOURCEDIR/$SOURCENAME/Logs/failedcompiles\"
+    fi
     exit 0
 " > packageinstallscript
 
@@ -740,7 +745,12 @@ function MakeAndInstall()
     fi
 
     #Copy the source logs correctly
-    cp "/$SOURCEDIR/$SOURCENAME/Logs/"* "$BUILDLOGDIR/$SOURCENAME/"
+    cp  "/$SOURCEDIR/$SOURCENAME/Logs/PackageInstallSource" "$BUILDLOGDIR/$SOURCENAME/"
+    cp  "/$SOURCEDIR/$SOURCENAME/Logs/PackagePostInstall" "$BUILDLOGDIR/$SOURCENAME/"
+    if [[ -e "/$SOURCEDIR/$SOURCENAME/Logs/failedcompiles" ]]
+    then
+      cat "/$SOURCEDIR/$SOURCENAME/Logs/failedcompiles" >> "$BUILDLOGDIR/failedcompiles"
+    fi
 
     #If the deb file exists, the control file exists, and the script is configured to make deb files, then just install the deb
   else
