Support using scalable tmpfs based on how much RAM is avalible to save wearing out SSDs as much as possible from temporary writes Based on how much RAM is free, an amount is set aside, and paticular features are redirected with bind mounts to use the RAM disk, based on the size of the RAM disk
Right now, the sizes need to be tuned, it's assuming that these need much more then they actually will take up


compile_all: cleanup the last package. Do it AFTER, so that if  one package build needs to be debugged directly, the pause statement can be placed easier, on the line, without having it deleted.
This part is still pending the overlayfs fix, for the srcbuild overlay to be enabled

git-svn-id: https://svn.code.sf.net/p/rebeccablackos/code@4471 b52b6941-3400-464c-9f42-43200397181c

diff --git a/rebeccablackos_files/usr/bin/compile_all b/rebeccablackos_files/usr/bin/compile_all
--- a/rebeccablackos_files/usr/bin/compile_all
+++ b/rebeccablackos_files/usr/bin/compile_all
@@ -36,6 +36,11 @@ function CompilePackage
   #compile_all is running to build the source
   if [[ "$argument" == build-only ]]
   then
+    #Cleanup any files in the srcbuild_overlay from the last build
+    if [[ $(mountpoint -q /; echo $?) == 0 ]]
+    then
+      rm -rf /tmp/srcbuild_overlay/*
+    fi
     echo "building $BUILDNAME"
     "/usr/bin/Compile/$BUILDNAME" build-only 2>&1
   fi
@@ -59,7 +64,7 @@ function CompilePackage
   then
     "/usr/bin/Compile/$BUILDNAME"
   fi
-
+  
 }
 
 #build these packages in this order. # symbol is a comment
