uvtty-launch: exit with the exit code of the command, don't run if the command is not found, and add bash completion
git-svn-id: https://svn.code.sf.net/p/rebeccablackos/code@7317 b52b6941-3400-464c-9f42-43200397181c

diff --git a/rebeccablackos_files/usr/bin/uvtty-launch b/rebeccablackos_files/usr/bin/uvtty-launch
--- a/rebeccablackos_files/usr/bin/uvtty-launch
+++ b/rebeccablackos_files/usr/bin/uvtty-launch
@@ -33,6 +33,12 @@ then
   exit 1
 fi
 
+if ! command -v $1 &> /dev/null
+then
+  echo "$0: Command '$1' not found"
+  exit 1
+fi
+
 if [[ -z $UvTTYName ]]
 then
   echo "UvTTYName variable not set. Not running under a UvTTY?"
@@ -77,5 +83,8 @@ fi
 
 #launch the program
 "$@"
+CommandResult=$?
 
 rm "$XDG_RUNTIME_DIR/uvtty/$UvTTYName/uvttysuspend"
+
+echo $CommandResult
