waylandloginmanager: WLM_NO_DBUS_RUN_SESSION is not needed in the session, don't export it, unexport variables instead of unsetting them, and handle terminating the systemd --user instance when the session is ended with wllogoff
git-svn-id: https://svn.code.sf.net/p/rebeccablackos/code@8061 b52b6941-3400-464c-9f42-43200397181c

diff --git a/rebeccablackos_files/usr/bin/waylandloginmanager b/rebeccablackos_files/usr/bin/waylandloginmanager
--- a/rebeccablackos_files/usr/bin/waylandloginmanager
+++ b/rebeccablackos_files/usr/bin/waylandloginmanager
@@ -150,6 +150,9 @@ function UserSessionWorker
   #prevent the WaylandLoginManager from being killed with CTRL+C
   trap '' 2
 
+  #Trap when exiting to run cleanup commands
+  trap 'UserSessionQuiter' EXIT
+
   #Enable job control
   set -m
 
@@ -228,8 +231,10 @@ function UserSessionWorker
   fi
   unset wlmforcepixman
 
+  WlmSDUserUnit="wlm-systemd-$WAYLAND_GUEST".service
+
   #If the session chooses to log to the journal, log the output to the log file as well
-  journalctl --user -f -b _SYSTEMD_USER_UNIT="wlm-systemd-$WAYLAND_GUEST".service + _SYSTEMD_SESSION=$XDG_SESSION_ID >> $WLM_SESSION_LOG 2>/dev/null &
+  journalctl --user -f -b _SYSTEMD_USER_UNIT=$WlmSDUserUnit + _SYSTEMD_SESSION=$XDG_SESSION_ID >> $WLM_SESSION_LOG 2>/dev/null &
   JournalctlPID=$!
 
   #Create an isolated systemd user session running under the current systemd user session. This allows multiple systemd managed sessions to allow to run as the same user at the same time. The initilization of the "systemctl --user" instance comes from xrdp.
@@ -240,7 +245,7 @@ function UserSessionWorker
     WLM_XDG_RUNTIME_DIR=/run/user/`id -u`/wlm-rd-"$WAYLAND_GUEST"
     WLM_DBUS_SESSION_BUS_ADDRESS="unix:path=$WLM_XDG_RUNTIME_DIR/bus"
     install -dDTm700 $WLM_XDG_RUNTIME_DIR
-    systemd-run --user -u "wlm-systemd-$WAYLAND_GUEST" -E XDG_RUNTIME_DIR="$WLM_XDG_RUNTIME_DIR" -E DBUS_SESSION_BUS_ADDRESS="$WLM_DBUS_SESSION_BUS_ADDRESS" systemd --user
+    systemd-run --user -u "$WlmSDUserUnit" -E XDG_RUNTIME_DIR="$WLM_XDG_RUNTIME_DIR" -E DBUS_SESSION_BUS_ADDRESS="$WLM_DBUS_SESSION_BUS_ADDRESS" systemd --user
     export DBUS_SESSION_BUS_ADDRESS=$WLM_DBUS_SESSION_BUS_ADDRESS
     export XDG_RUNTIME_DIR=$WLM_XDG_RUNTIME_DIR
     #Wait for the socket to be active
@@ -301,8 +306,9 @@ function UserSessionWorker
   else
     if [[ -z $WLM_GDB_SESSION ]]
     then
-      unset WAYLAND_HOST
-      unset WAYLAND_GUEST
+      export -n WAYLAND_HOST
+      export -n WAYLAND_GUEST
+      export -n WLM_NO_DBUS_RUN_SESSION
     fi
   fi
 
@@ -346,17 +352,23 @@ function UserSessionWorker
     fi
   fi
 
-  #Stop the nested systemctl --user session if it was started.
-  if [[ $WLM_NO_DBUS_RUN_SESSION == 1 ]]
-  then
-    XDG_RUNTIME_DIR=$BASE_XDG_RUNTIME_DIR DBUS_SESSION_BUS_ADDRESS=$BASE_DBUS_SESSION_BUS_ADDRESS systemctl --user stop "wlm-systemd-$WAYLAND_GUEST"
-  fi
+  UserSessionQuiter
 
   #Write the error code into the logfile
   echo -e "\nSession exited with the error code: $SessionReturnCode" >> $WLM_SESSION_LOG
   $SLEEPCMD 1
   TerminateJobPID $JournalctlPID 15 0
   exit
+}
+
+#Function that UserSessionWorker calls when exiting. It takes no arguments
+function UserSessionQuiter
+{
+  #Stop the nested systemctl --user session if it was started.
+  if [[ $WLM_NO_DBUS_RUN_SESSION == 1 ]]
+  then
+    XDG_RUNTIME_DIR=$BASE_XDG_RUNTIME_DIR DBUS_SESSION_BUS_ADDRESS=$BASE_DBUS_SESSION_BUS_ADDRESS systemctl --user stop "$WlmSDUserUnit"
+  fi
 }
 
 #Function that uses a bash builtin to check the existance of files, it takes 2 arguments, the files to probe, the files may have wildcards and regex
