waylandloginmanager: improve lockfile handling, with the old one, someone could rename the script and use that to make a second instance. This now uses a fd and the pid, to try to account for pid recycling. (As in it stops, some other process gets the PID, where the symlink to it in /proc is then still valid)
git-svn-id: https://svn.code.sf.net/p/rebeccablackos/code@5706 b52b6941-3400-464c-9f42-43200397181c

diff --git a/rebeccablackos_files/usr/bin/waylandloginmanager b/rebeccablackos_files/usr/bin/waylandloginmanager
--- a/rebeccablackos_files/usr/bin/waylandloginmanager
+++ b/rebeccablackos_files/usr/bin/waylandloginmanager
@@ -92,6 +92,8 @@
   #~/wlsessionlogs/waylandhost_($SEAT).log : This log is for the host Wayland server that gets started for Wayland sessions that run on other Wayland servers
 
 #Runtime Files:
+  #/run/waylandloginmanager/pidfile: an empty file waylandloginmanager attempts to open with file descriptor #1023 to assist with locking
+  #/run/waylandloginmanager/waylandloginmanager.lock: a symlink to /proc/$$/fd/1023 , when the symlink is broken, waylandloginmanager is not running. (and fd 1023 is used to try to account for recycled pids)
   #/run/waylandloginmanager/autologinran: Denotes that the autologin process has run already, after startup (since /run is a tmpfs). This prevents autologin when the service is restarted
   #/run/waylandloginmanager/sessiondata: Stores data for user switching so that the session list can be reloaded if waylandloginmanager restarts. As it's stored in /run which is a tmpfs, there should be no risk of one from a previous boot giving it false data
   #/run/waylandloginmanager/usrbinwaylandloginmanager.lock: (the file name is generated by the path that this script is in, removing the slashes). this prevents two instances of the waylandloginmanager from starting. 
@@ -442,39 +444,42 @@ function PrepareLoginManager
   export LOGINMANAGERDISPLAYUID=$(id $LOGINMANAGERDISPLAYUSER -u)
   export XDG_RUNTIME_DIR=/run/user/$LOGINMANAGERDISPLAYUID
 
-  #Create the waylandloginmanager folder in /run for FIFOs and lockfiles
-  mkdir -p /run/waylandloginmanager
-  touch /run/waylandloginmanager/fifolock
-
-  #Detect another instance, by creating a testing a lockfile, which is a symlink to /proc/pid/cmdline, and making sure the second line of /proc/pid/cmdline matches (as it's the path to the script).
-  SCRIPTPATH=$(readlink -f "$0")
-  SCRIPTNAME=$(echo "$SCRIPTPATH" | sed 's\/\\g')
-  LOCKSCRIPT=$(readlink -f "$(strings -a "/run/waylandloginmanager/$SCRIPTNAME.lock" 2>/dev/null | sed -n 2p)" )
-  if [[ "$SCRIPTPATH" != "$LOCKSCRIPT" ]]
-  then
-    rm -r "/run/waylandloginmanager/$SCRIPTNAME.lock" 2>/dev/null
-    ln -s /proc/"$$"/cmdline "/run/waylandloginmanager/$SCRIPTNAME.lock"
-  else
-    echo "Error: Another instance is already running"
-    exit 1
-  fi
-  #second check to make sure this instance 'won' as a second instance could report success, and execute as the first instance is OK to run, but before it creates the lockfile
-  #this ensures that the linked /proc/pid/cmdline is this pid
-  LOCKPROCPATH=$(dirname $(readlink "/run/waylandloginmanager/$SCRIPTNAME.lock" ))
-  THISPROCPATH=/proc/$$
-  if [[ $LOCKPROCPATH != $THISPROCPATH ]]
-  then
-    echo "Error: Another instance is already running"
-    exit 1
-  fi
-
   #Require root privlages
   if [[ $UID != 0 ]]
   then
     echo "Must be run as root."
     exit 1
   fi
-  
+
+  #Create the waylandloginmanager folder in /run for FIFOs and lockfiles
+  mkdir -p /run/waylandloginmanager
+  touch /run/waylandloginmanager/fifolock
+
+  #Create and open an empty file, with file descriptor #1023.
+  touch /run/waylandloginmanager/pidfile
+  exec 1023<> /run/waylandloginmanager/pidfile
+
+  #Detect another instance, testing if the lockfile path to the previous waylandloginmanager's file descriptor 1023 is invalid
+  if [[  ! -e "/run/waylandloginmanager/waylandloginmanager.lock"  ]]
+  then
+    #Link this proccess's file descriptor #1023 to the lock file
+    #When this path is valid, this check will not allow the new instance to run, because there already is one
+    rm -r "/run/waylandloginmanager/waylandloginmanager.lock" 2>/dev/null
+    ln -s /proc/"$$"/fd/1023 "/run/waylandloginmanager/waylandloginmanager.lock"
+  else
+    echo "Error: Another instance is already running"
+    exit 1
+  fi
+  #second check to make sure this instance 'won' as a second instance could report success, and execute as the first instance is OK to run, but before it creates the lockfile
+  #this ensures that the linked /proc/pid/cmdline is this pid
+  LOCKPROCPATH=$(dirname $(readlink "/run/waylandloginmanager/waylandloginmanager.lock" ))
+  THISPROCPATH=/proc/$$/fd/1023
+  if [[ $LOCKPROCPATH != $THISPROCPATH ]]
+  then
+    echo "Error: Another instance is already running"
+    exit 1
+  fi
+
   #Prepare logging for the loginmanagerdisplay
 
   #Older versions of the waylandloginmanager used to log to /var/log/waylandloginmanager , now /var/log/waylandloginmanager is a folder
