waylandloginmanager: fix exit handling when there are no valid wsessions for a seat
The reduction in the number of subprocesses called, is probably at the best possible. 149 called by waylandloginmanager for when there are 3 seats all autologging in, 78 for one seat, and most of them can't be handled by bash builtins. (using the snoopy utility on a test computer)

git-svn-id: https://svn.code.sf.net/p/rebeccablackos/code@5754 b52b6941-3400-464c-9f42-43200397181c

diff --git a/rebeccablackos_files/usr/bin/waylandloginmanager b/rebeccablackos_files/usr/bin/waylandloginmanager
--- a/rebeccablackos_files/usr/bin/waylandloginmanager
+++ b/rebeccablackos_files/usr/bin/waylandloginmanager
@@ -1437,7 +1437,7 @@ function ChooseSessionType
     CancelOrOK=$?
     if [[ $CancelOrOK != 0 ]]
     then
-      exit 0
+      return 1
     fi
     WSESSIONDATA=${WSESSIONARRAY[$((0+WSESSIONNUMBER*10))]}$'\n'${WSESSIONARRAY[$((1+WSESSIONNUMBER*10))]}$'\n'${WSESSIONARRAY[$((2+WSESSIONNUMBER*10))]}$'\n'${WSESSIONARRAY[$((3+WSESSIONNUMBER*10))]}$'\n'${WSESSIONARRAY[$((4+WSESSIONNUMBER*10))]}$'\n'${WSESSIONARRAY[$((5+WSESSIONNUMBER*10))]}$'\n'${WSESSIONARRAY[$((6+WSESSIONNUMBER*10))]}$'\n'${WSESSIONARRAY[$((7+WSESSIONNUMBER*10))]}$'\n'${WSESSIONARRAY[$((8+WSESSIONNUMBER*10))]}$'\n'
 
@@ -1446,7 +1446,7 @@ function ChooseSessionType
     unset WSESSIONNUMBER
     $ZENITYCMD --width=500 --warning --text="No sessions are installed, configured correctly, or supported by the hardware in this seat." 2>/dev/null
     WriteToLog "No sessions are installed in $WSESSIONSPATH, configured correctly, or supported by the hardware in this seat, $CurrentHandleSeat ."
-    exit 1
+    return 1
   fi
 }
 
@@ -1810,6 +1810,10 @@ function AuthenticateUser
     export USERHOME=$(eval echo ~$LOGINUSER)
     #Prompt for the session type
     ChooseSessionType "$1"
+    if [[ $? != 0 ]]
+    then
+      return 0
+    fi
 
     #if the password and username is correct, start the session
     if [[ $1 == seat0 ]]
@@ -1824,8 +1828,8 @@ function AuthenticateUser
     #report success
     return 0
   else
-      #report failure
-      return 1
+    #report failure
+    return 1
   fi
 }
 
