wlsudo: Exit if there is no running wayland display
git-svn-id: https://svn.code.sf.net/p/rebeccablackos/code@8933 b52b6941-3400-464c-9f42-43200397181c

diff --git a/rebeccablackos_files/usr/bin/wlsudo b/rebeccablackos_files/usr/bin/wlsudo
--- a/rebeccablackos_files/usr/bin/wlsudo
+++ b/rebeccablackos_files/usr/bin/wlsudo
@@ -23,6 +23,13 @@
 export WLSUDO=1
 export SUDO_ASKPASS="$0"
 
+wayland-info &> /dev/null
+WaylandPingResult=$?
+if [[ $WaylandPingResult != 0 ]]
+then
+  echo "wlsudo: Could not make a connection to a Wayland display"
+  exit 1
+fi
 
 if [[ -z $WLSUDO_CMD ]]
 then
