Work in progress
git-svn-id: https://svn.code.sf.net/p/rebeccablackos/code@1019 b52b6941-3400-464c-9f42-43200397181c

diff --git a/rebeccablacklinux_files/usr/libexec/wayland_helpers/login-test-helper b/rebeccablacklinux_files/usr/libexec/wayland_helpers/login-test-helper
--- a/rebeccablacklinux_files/usr/libexec/wayland_helpers/login-test-helper
+++ b/rebeccablacklinux_files/usr/libexec/wayland_helpers/login-test-helper
@@ -1,4 +1,4 @@
-#! /bin/bash
+#! /usr/bin/expect
 #    Copyright (c) 2012, nerdopolis (or n3rdopolis) <bluescreen_avenger@version.net>
 #
 #    This file is part of RebeccaBlackLinux.
@@ -16,16 +16,24 @@
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-#Require root privlages
-if [[ $UID != 0 ]]
-then
-echo "Must be run as root."
-exit
-fi
+#using the password argument sent, put it into a variable
+set LOGINUSER $::env(LOGINUSER)
+set password [lindex $argv 0]
 
-echo "Enter Password for $LOGONUSER"
-su $LOGONUSER -c /bin/true 
-RESULT=$?
-echo $RESULT > /run/loginmanager_data.$loginmanagerpid.$SessionNumber
-#Test login to bin true
-#If it works su to user
+#test with /bin/true, before trying the real login so that the password fail result can be returned to the main script
+su $LOGINUSER -c /bin/true
+expect "Password:"
+
+send "$password\r";
+
+catch wait result
+set status [lindex $result 3]
+
+if { $status == 0 } {
+spawn su $LOGINUSER -c /usr/bin/wlsessionmanager
+expect "Password:"
+
+send "$password\r";
+
+interact
+} else {exit 1}
