waylandloginmanager: create a waylandloginmanager user, instead of using daemon
git-svn-id: https://svn.code.sf.net/p/rebeccablackos/code@3158 b52b6941-3400-464c-9f42-43200397181c

diff --git a/rebeccablacklinux_files/usr/bin/waylandloginmanager b/rebeccablacklinux_files/usr/bin/waylandloginmanager
--- a/rebeccablacklinux_files/usr/bin/waylandloginmanager
+++ b/rebeccablacklinux_files/usr/bin/waylandloginmanager
@@ -223,6 +223,12 @@ function PrepareLoginManager
     exit
   fi
 
+  if [[ $(id waylandloginmanager &>/dev/null; echo $? ) == 1 ]]
+  then
+    logger -t waylandloginmanager "Error: The user waylandloginmanager does NOT exist. Creating the user account..." -s  >>/var/log/waylandloginmanager 2>&1
+    adduser --no-create-home --home=/etc/loginmanagerdisplay --shell=/bin/bash --disabled-password --system waylandloginmanager
+  fi
+
   #prevent the WaylandLoginManager from being killed with CTRL+C
   trap '' 2
 
@@ -243,11 +249,11 @@ function PrepareLoginManager
   #The LOGINMANAGERDISPLAYHOME variable controls where the home directory for the user that calls the loginmanagerdisplay the weston.ini that has the fifo command helpers needs to be in $LOGINMANAGERDISPLAYHOME/.config/
   export LOGINMANAGERDISPLAYHOME=/etc/loginmanagerdisplay/
   #User that the zenity dialogs and the loginmanagerdisplay (weston instance for the waylandloginmanager runs as
-  export LOGINMANAGERDISPLAYUSER=daemon
+  export LOGINMANAGERDISPLAYUSER=waylandloginmanager
   #User that the su test in AuthenticateUser user runs as
-  export PROBETESTUSER=daemon
+  export PROBETESTUSER=waylandloginmanager
   #User that reads from the loginmanager_control FIFO, and filters the command sent to it to loginmanager_listener
-  export FIFOREADERUSER=daemon
+  export FIFOREADERUSER=waylandloginmanager
   #Get the UID of the $LOGINMANAGERDISPLAYUSER
   export LOGINMANAGERDISPLAYUID=$(id $LOGINMANAGERDISPLAYUSER -u)
   #Set the default path for weston
